### ISSUE TITLE
Renommer la table "analyses" en "gps_data"

### ISSUE THREAD

**Issue by ktalbi** [PnEcrins/FollowDem-admin#9]
Vérifier les noms des autres tables selon:
https://user-images.githubusercontent.com/4418840/42826125-f83389a2-89e3-11e8-9f33-c666559ab7c7.jpg

https://github.com/PnEcrins/FollowDem/issues/48#issuecomment-405620938

**Comment by camillemonchicourt** [comment]
Fait dans commit https://github.com/PnEcrins/FollowDem-admin/commit/330ce7649f77e9c461be369c49569597456155c1
Et MCD complété ici : https://github.com/PnEcrins/FollowDem/issues/48#issuecomment-585165731
